### ISSUE TITLE
Crash in grade crossing replacement

### ISSUE THREAD

**Issue by GoogleCodeExporter** [teshiron/teshinet#21]
```
In the event the vehicle is deleted between the start of the event handler and 
the call to the superlib function, the AI will crash in SuperLib because the 
tile is null.
```

Original issue reported on code.google.com by `evend...@gmail.com` on 25 Dec 2011 at 6:24

**Comment by teshiron** [comment]
I think this is already resolved by referencing the location of the crash from the event itself and not the dead vehicle.
